---
openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0.0.1
  description: API documentation for To-Do Application
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  "/todos/{id}":
    get:
      tags:
        - to-do-controller
      operationId: getTodo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/ToDoItemResponseDTO"
    put:
      tags:
        - to-do-controller
      operationId: updateTodo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/ToDoItemRequestDTO"
        required: true
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/ToDoItemResponseDTO"
    delete:
      tags:
        - to-do-controller
      operationId: deleteTodo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
  "/todos":
    get:
      tags:
        - to-do-controller
      operationId: getAllTodos
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/ToDoItemResponseDTO"
    post:
      tags:
        - to-do-controller
      operationId: createTodo
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/ToDoItemRequestDTO"
        required: true
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/ToDoItemResponseDTO"
components:
  schemas:
    ToDoItemRequestDTO:
      type: object
      properties:
        title:
          type: string
          minLength: 1
        description:
          type: string
          minLength: 1
        completed:
          type: boolean
      required:
        - description
        - title
    ToDoItemResponseDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        completed:
          type: boolean
